spring.cloud.config.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/EnviromentProject
spring.datasource.username=postgres
spring.datasource.password=linux123

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/EnviromentProject

# Credenciales de GestoPago
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.token-estatico=qmzAAEYFmqQbIT/Ktxme8FDV343iYQPwVJM4T39cEinWq1yjc1pp9oxSo4Rjmo5Fk27YzkCDaCr5RM4xtGZNCBZk1MH1tMNbykJ/WzfVjxSEXc9FERnZJPsVuFcAgfsfHmEYEfsLSmLZgovuGmnpDA==

# Timeouts para Feign (Evita cuelgues del servidor)
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000

#Configuración CRON
gestopago.sync.cron=0 * * * * ?
